<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-K6HNVQA" failures="1" tests="4" name="Payment" time="0.13" errors="0" timestamp="02 Jul 2018 04:40:00 GMT">
  <testcase classname="Test.Day1" name="Demo" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Day1.Demo(Day1.java:10)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="Test.Day2" name="checkpoint" time="0.005"/>
  <testcase classname="Test.Day4" name="mobileLoginCarLoan" time="0.006"/>
  <testcase classname="Test.Day4" name="webLoginCarLoan" time="0.0"/>
  <testcase classname="Test.Day4" name="apiLoginCarLoan" time="0.0">
    <ignored/>
  </testcase> <!-- apiLoginCarLoan -->
  <testcase classname="Test.Day1" name="Check" time="0.0">
    <ignored/>
  </testcase> <!-- Check -->
</testsuite> <!-- Payment -->
